//Crea una matriu de 3 files i 5 columnes. 
// El contingut de les cel·les ha de ser un indicador de la fila i la columna de manera que la primera fila quede f1c1, f1c2, f1c3...
//Recorre tota la matriu empalmant dos forEach() i mostra el resultat en consola.